apiVersion: v2
name: pgextassure
description: Hardened PgExtAssure Admission Gateway with mandatory mTLS ingress
type: application
version: 0.1.0-alpha.14
appVersion: "0.1.0-alpha.14"
kubeVersion: ">=1.28.0-0"
home: https://github.com/borborich/pgextassure
sources:
  - https://github.com/borborich/pgextassure
maintainers:
  - name: PgExtAssure contributors
